# https://medium.com/@gottfrois/github-actions-for-elixir-phoenix-app-with-cache-6ca33f628459

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  LC_CTYPE: 'en_US.UTF-8'
  LANGUAGE: 'en_US.UTF-8'
  MIX_ENV: test
jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: [1.14.1]
        otp: [25.1.1]

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Retrieve Cached Dependencies
        uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            deps
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}

      - name: Install dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: Run tests
        run: mix test
